# Generated by Django 4.1.2 on 2022-11-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Направление')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('code', models.CharField(max_length=10, verbose_name='Код направления')),
                ('ct_complexity_hard', models.FloatField()),
                ('ct_complexity_easy', models.FloatField()),
                ('ct_mark_3', models.FloatField()),
                ('ct_mark_4', models.FloatField()),
                ('ct_mark_5', models.FloatField()),
                ('ct_practical_yes', models.FloatField()),
                ('ct_practical_no', models.FloatField()),
                ('ct_jobs_yes', models.FloatField()),
                ('ct_jobs_no', models.FloatField()),
                ('ct_students', models.IntegerField()),
                ('ct_vacancy', models.IntegerField()),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Государтсвенный стандарт',
                'verbose_name_plural': 'Государтсвенные стандарты',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('university', models.CharField(max_length=255, verbose_name='Университет')),
                ('expirience', models.PositiveSmallIntegerField(verbose_name='Опыт преподавания')),
                ('disciplines', models.TextField(verbose_name='Преподаваемые дисциплины')),
                ('education', models.TextField(verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
